### ISSUE TITLE
ckeditor table attributes 

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/sitenow#336]
No table attr are available for a ckeditor table. I've tried adding them to filtered_html but they didn't seem to work.

**Comment by joewhitsitt** [comment]
PR #337 provides table properties, but style is stripped due to XSS concerns. There is an issue: https://www.drupal.org/project/drupal/issues/2785483

For now it looks like we don't support the table drag resize and should consider allowing classes on all the things so that editors can use the built-in bootstrap utility classes: https://getbootstrap.com/docs/4.3/utilities/sizing/

**Comment by adamdelaney** [comment]
We should remove all table configuration that implements it's properties via style attribute.

**Comment by joewhitsitt** [comment]
Looks like width, cell padding, cell spacing and align all get overridden by the bootstrap table class

**Comment by joewhitsitt** [comment]
Added PR to remove certain attributes from the dialog. tableresize is part of build-config.js that is part of core. Still looking into the right click table actions.

To add bootstrap checkboxes for table-hover, table-striped, etc. we would need to use a different table plugin or create our own that works with bootstrap 4's additional options.
https://ckeditor.com/cke4/addon/bootstrapTable
https://ckeditor.com/cke4/addon/bttable

**Comment by joewhitsitt** [comment]
except for tableresize (core build) i think this is now in a good spot.

**Comment by joewhitsitt** [comment]
Created a separate issue for tableresize #346. Everything else is done/fixed/handled differently.
